fix(Cargo.toml): patch out `form_urlencoded` and `percent-encoding` too
Fixes:
```
running: RUSTC_BOOTSTRAP="1" "/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "--print=target-spec-json-schema" "-Zunstable-options" (failure_mode=Exit) (created at src/bootstrap/src/core/build_steps/dist.rs:628:21, executed at src/bootstrap/src/core/build_steps/dist.rs:632:24)
Vendoring sources to "/mnt/redox/recipes/dev/rust/source"
running: cd "/mnt/redox/recipes/dev/rust/source" && RUSTC="/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build/build/x86_64-unknown-linux-gnu/stage0/bin/rustc" RUSTC_BOOTSTRAP="1" "/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "vendor" "--versioned-dirs" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/cargo/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/clippy/clippy_test_deps/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/rust-analyzer/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/compiler/rustc_codegen_cranelift/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/compiler/rustc_codegen_gcc/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/library/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/bootstrap/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/rustbook/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/rustc-perf/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/opt-dist/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/doc/book/packages/trpl/Cargo.toml" "/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build/build/tmp/generate-copyright-vendor" (failure_mode=Exit) (created at src/bootstrap/src/core/build_steps/vendor.rs:79:23, executed at src/bootstrap/src/core/build_steps/vendor.rs:111:26)
error: failed to sync

Caused by:
  found duplicate version of package `form_urlencoded v1.2.2` vendored from two sources:

  	source 1: registry `crates-io`
  	source 2: https://github.com/Andy-Python-Programmer/rust-url/#640e308c
Command `cd "/mnt/redox/recipes/dev/rust/source" && RUSTC="/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build/build/x86_64-unknown-linux-gnu/stage0/bin/rustc" RUSTC_BOOTSTRAP="1" "/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "vendor" "--versioned-dirs" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/cargo/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/clippy/clippy_test_deps/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/rust-analyzer/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/compiler/rustc_codegen_cranelift/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/compiler/rustc_codegen_gcc/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/library/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/bootstrap/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/rustbook/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/rustc-perf/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/tools/opt-dist/Cargo.toml" "--sync" "/mnt/redox/recipes/dev/rust/source/src/doc/book/packages/trpl/Cargo.toml" "/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build/build/tmp/generate-copyright-vendor" (failure_mode=Exit)` failed with exit code 101
Created at: src/bootstrap/src/core/build_steps/vendor.rs:79:23
Executed at: src/bootstrap/src/core/build_steps/vendor.rs:111:26

--- STDOUT vvv

Traceback (most recent call last):
  File "/mnt/redox/recipes/dev/rust/source/x.py", line 53, in <module>
    bootstrap.main()
    ~~~~~~~~~~~~~~^^
  File "/mnt/redox/recipes/dev/rust/source/src/bootstrap/bootstrap.py", line 1395, in main
    bootstrap(args)
    ~~~~~~~~~^^^^^^
  File "/mnt/redox/recipes/dev/rust/source/src/bootstrap/bootstrap.py", line 1370, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/redox/recipes/dev/rust/source/src/bootstrap/bootstrap.py", line 237, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build/build/bootstrap/debug/bootstrap install --config config.toml --jobs 32
redoxer env: exit status: 1

failed to build: "failed to run cd \"/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build\" && COOKBOOK_BUILD=\"/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/build\" COOKBOOK_HOST_TARGET=\"x86_64-unknown-linux-gnu\" COOKBOOK_MAKE_JOBS=\"32\" COOKBOOK_NAME=\"rust\" COOKBOOK_RECIPE=\"/mnt/redox/recipes/dev/rust\" COOKBOOK_REDOXER=\"/mnt/redox/target/release/cookbook_redoxer\" COOKBOOK_ROOT=\"/mnt/redox\" COOKBOOK_SOURCE=\"/mnt/redox/recipes/dev/rust/source\" COOKBOOK_STAGE=\"/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/stage.tmp\" COOKBOOK_SYSROOT=\"/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/sysroot\" COOKBOOK_TOOLCHAIN=\"/mnt/redox/recipes/dev/rust/target/x86_64-unknown-redox/toolchain\" COOKBOOK_VERBOSE=\"1\" TARGET=\"x86_64-unknown-redox\" \"/mnt/redox/target/release/cookbook_redoxer\" \"env\" \"bash\" \"-ex\": exited with status exit status: 1"
```

Signed-off-by: Anhad Singh <andypython@protonmail.com>